//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class producttable
    {
        public int id { get; set; }
        public string productname { get; set; }
        public Nullable<double> price { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> datepurchased { get; set; }
    }
}
